LOCALDIR := module

ALLOBJS	+= \
	$(LOCALDIR)/symtab.o \
	$(LOCALDIR)/symbols.o \
	$(LOCALDIR)/ram-segments.o \
	$(LOCALDIR)/module_loader_arm.o \
	$(LOCALDIR)/module_loader.o

ALLOBJS	+= $(LOCALDIR)/hello.ko
