LOCALDIR := arch/arm

ALLOBJS-$(CONFIG_ARCH_ARM) += \
	$(LOCALDIR)/proc-arm926.o \
	$(LOCALDIR)/arch_task.o \
	$(LOCALDIR)/arch_irq.o \
	$(LOCALDIR)/ops.o \
	$(LOCALDIR)/kernel/module.o \
	$(LOCALDIR)/lib/strchr.o \
	$(LOCALDIR)/arch.o \
	$(LOCALDIR)/mmu.o \
	$(LOCALDIR)/halt.o
