LOCALDIR := kernel

ALLOBJS += \
	$(LOCALDIR)/main.o \
	$(LOCALDIR)/sched_fifo.o \
	$(LOCALDIR)/sched.o \
	$(LOCALDIR)/task.o \
	$(LOCALDIR)/printk.o \
	$(LOCALDIR)/malloc.o \
	$(LOCALDIR)/timer.o \
	$(LOCALDIR)/semaphore.o \
	$(LOCALDIR)/symtab.o \
	$(LOCALDIR)/ram-segments.o \
	$(LOCALDIR)/module.o
