LOCALDIR := kernel

ALLOBJS-y += \
	$(LOCALDIR)/sched_fifo.o \
	$(LOCALDIR)/sched.o \
	$(LOCALDIR)/task.o \
	$(LOCALDIR)/printk.o \
	$(LOCALDIR)/timer.o \
	$(LOCALDIR)/semaphore.o \
	$(LOCALDIR)/symbols.o \
	$(LOCALDIR)/symtab.o \
	$(LOCALDIR)/module.o \
	$(LOCALDIR)/debug.o \
	$(LOCALDIR)/wait_queue.o \
	$(LOCALDIR)/completion.o \
	$(LOCALDIR)/workqueue.o

