LOCALDIR := kernel

ALLOBJS-y += \
	$(LOCALDIR)/sched_fifo.o \
	$(LOCALDIR)/sched.o \
	$(LOCALDIR)/task.o \
	$(LOCALDIR)/printk.o \
	$(LOCALDIR)/timer.o \
	$(LOCALDIR)/semaphore.o \
	$(LOCALDIR)/symtab.o \
	$(LOCALDIR)/module.o \
	$(LOCALDIR)/debug.o
