#include <module/symbols.h>
extern int __aeabi_idiv();
extern int __aeabi_idiv0();
extern int __aeabi_idivmod();
extern int __aeabi_ldiv0();
extern int __aeabi_uidiv();
extern int __aeabi_uidivmod();
extern int __bss_start();
extern int __console_init();
extern int __div0();
extern int __divsi3();
extern int __free_pages();
extern int __heap();
extern int __puts();
extern int __puts_early();
extern int __udivsi3();
extern int __umodsi3();
extern int _dvprintf();
extern int _end();
extern int _start();
extern int abort_stack();
extern int abort_stack_top();
extern int all_task();
extern int alloc_kmodule();
extern int alloc_pages();
extern int apply_relocate();
extern int arch_context_switch();
extern int arch_cpu_reset();
extern int arch_disable_ints();
extern int arch_early_init();
extern int arch_enable_ints();
extern int arch_idle();
extern int arch_task_initialize();
extern int arm_context_switch();
extern int arm_irq();
extern int arm_mmu_create_mapping();
extern int arm_mmu_init();
extern int arm_mmu_map_page();
extern int arm_mmu_map_section();
extern int arm_mmu_remap_evt();
extern int arm_mmu_unmap_section();
extern int clean_user_space();
extern int commands();
extern int console_buffer();
extern int console_init();
extern int cpu_arm926_do_idle();
extern int cpu_arm926_reset();
extern int cpu_arm926_switch_mm();
extern int critical_section_count();
extern int current_task();
extern int current_time();
extern int data_abort();
extern int dirent_trim();
extern int down();
extern int exception_init();
extern int fat12fs_opvector();
extern int fat16fs_opvector();
extern int fat32fs_opvector();
extern int fat_dirent_lookup();
extern int fat_fs();
extern int fat_next_cluster12();
extern int fat_next_cluster16();
extern int fat_next_cluster32();
extern int fat_read_cluster();
extern int fat_read_sector();
extern int fatfs_dir_vops();
extern int fatfs_pread();
extern int fatfs_vops();
extern int fd_alloc();
extern int fd_assign();
extern int fd_free();
extern int file_alloc();
extern int fiq();
extern int fp_free();
extern int fp_get();
extern int free_kmodule();
extern int free_pages();
extern int fs_root();
extern int get_cpsr();
extern int getchar();
extern int help();
extern int init_shell();
extern int initial_task_func();
extern int insert_to_free_area();
extern int irq();
extern int irq_save_spot();
extern int is_pllc_invalid();
extern int k_module_root();
extern int kernel_pgd();
extern int kfree();
extern int kmain();
extern int kmalloc();
extern int kmalloc_init();
extern int kmod_sem();
extern int kmsg_dump();
extern int load_kmodule();
extern int mask_interrupt();
extern int memcmp();
extern int memcpy();
extern int memmove();
extern int memset();
extern int mod_output_ops();
extern int module_unknown();
extern int next_task();
extern int oneshot_timer_add();
extern int pFun();
extern int page_address();
extern int page_alloc_init();
extern int periodic_timer_add();
extern int platform_fiq();
extern int platform_init();
extern int platform_init_interrupts();
extern int platform_init_timer();
extern int platform_irq();
extern int platform_set_periodic_timer();
extern int pllc_to_busclk();
extern int prefetch_abort();
extern int print_free_list();
extern int printk();
extern int putchar();
extern int puts();
extern int readline();
extern int register_filesystem();
extern int register_int_handler();
extern int reserved();
extern int reset();
extern int run_command();
extern int sched_class_fifo();
extern int sched_fifo_init();
extern int sched_init();
extern int scheduler();
extern int sem();
extern int shell_register_command();
extern int shell_unregister_command();
extern int show_logo();
extern int simple_strtoul();
extern int slob_alloc();
extern int slob_free();
extern int slob_new_pages();
extern int slob_page_alloc();
extern int stack_top();
extern int strcat();
extern int strchr();
extern int strcmp();
extern int strcpy();
extern int strlen();
extern int strncmp();
extern int strncpy();
extern int symtab_lookup();
extern int syscall();
extern int task_alloc();
extern int task_bitmap();
extern int task_create();
extern int task_create_init();
extern int task_exit();
extern int task_free();
extern int task_init();
extern int task_schedule();
extern int task_sleep();
extern int timer_delete();
extern int timer_init();
extern int timer_list();
extern int timer_tick();
extern int undefined();
extern int undefined_stack();
extern int undefined_stack_top();
extern int unmask_interrupt();
extern int up();
extern int vfs_close();
extern int vfs_lookup();
extern int vfs_mount();
extern int vfs_open();
extern int vfs_read();
extern int virt_to_page();
extern int vsnprintf();
extern int zones();
extern int zones_name();
const int symbols_nelts = 177;
const struct symbols symbols[177] = {
{"__aeabi_idiv", (void *)__aeabi_idiv},
{"__aeabi_idiv0", (void *)__aeabi_idiv0},
{"__aeabi_idivmod", (void *)__aeabi_idivmod},
{"__aeabi_ldiv0", (void *)__aeabi_ldiv0},
{"__aeabi_uidiv", (void *)__aeabi_uidiv},
{"__aeabi_uidivmod", (void *)__aeabi_uidivmod},
{"__bss_start", (void *)__bss_start},
{"__console_init", (void *)__console_init},
{"__div0", (void *)__div0},
{"__divsi3", (void *)__divsi3},
{"__free_pages", (void *)__free_pages},
{"__heap", (void *)__heap},
{"__puts", (void *)__puts},
{"__puts_early", (void *)__puts_early},
{"__udivsi3", (void *)__udivsi3},
{"__umodsi3", (void *)__umodsi3},
{"_dvprintf", (void *)_dvprintf},
{"_end", (void *)_end},
{"_start", (void *)_start},
{"abort_stack", (void *)abort_stack},
{"abort_stack_top", (void *)abort_stack_top},
{"all_task", (void *)all_task},
{"alloc_kmodule", (void *)alloc_kmodule},
{"alloc_pages", (void *)alloc_pages},
{"apply_relocate", (void *)apply_relocate},
{"arch_context_switch", (void *)arch_context_switch},
{"arch_cpu_reset", (void *)arch_cpu_reset},
{"arch_disable_ints", (void *)arch_disable_ints},
{"arch_early_init", (void *)arch_early_init},
{"arch_enable_ints", (void *)arch_enable_ints},
{"arch_idle", (void *)arch_idle},
{"arch_task_initialize", (void *)arch_task_initialize},
{"arm_context_switch", (void *)arm_context_switch},
{"arm_irq", (void *)arm_irq},
{"arm_mmu_create_mapping", (void *)arm_mmu_create_mapping},
{"arm_mmu_init", (void *)arm_mmu_init},
{"arm_mmu_map_page", (void *)arm_mmu_map_page},
{"arm_mmu_map_section", (void *)arm_mmu_map_section},
{"arm_mmu_remap_evt", (void *)arm_mmu_remap_evt},
{"arm_mmu_unmap_section", (void *)arm_mmu_unmap_section},
{"clean_user_space", (void *)clean_user_space},
{"commands", (void *)commands},
{"console_buffer", (void *)console_buffer},
{"console_init", (void *)console_init},
{"cpu_arm926_do_idle", (void *)cpu_arm926_do_idle},
{"cpu_arm926_reset", (void *)cpu_arm926_reset},
{"cpu_arm926_switch_mm", (void *)cpu_arm926_switch_mm},
{"critical_section_count", (void *)critical_section_count},
{"current_task", (void *)current_task},
{"current_time", (void *)current_time},
{"data_abort", (void *)data_abort},
{"dirent_trim", (void *)dirent_trim},
{"down", (void *)down},
{"exception_init", (void *)exception_init},
{"fat12fs_opvector", (void *)fat12fs_opvector},
{"fat16fs_opvector", (void *)fat16fs_opvector},
{"fat32fs_opvector", (void *)fat32fs_opvector},
{"fat_dirent_lookup", (void *)fat_dirent_lookup},
{"fat_fs", (void *)fat_fs},
{"fat_next_cluster12", (void *)fat_next_cluster12},
{"fat_next_cluster16", (void *)fat_next_cluster16},
{"fat_next_cluster32", (void *)fat_next_cluster32},
{"fat_read_cluster", (void *)fat_read_cluster},
{"fat_read_sector", (void *)fat_read_sector},
{"fatfs_dir_vops", (void *)fatfs_dir_vops},
{"fatfs_pread", (void *)fatfs_pread},
{"fatfs_vops", (void *)fatfs_vops},
{"fd_alloc", (void *)fd_alloc},
{"fd_assign", (void *)fd_assign},
{"fd_free", (void *)fd_free},
{"file_alloc", (void *)file_alloc},
{"fiq", (void *)fiq},
{"fp_free", (void *)fp_free},
{"fp_get", (void *)fp_get},
{"free_kmodule", (void *)free_kmodule},
{"free_pages", (void *)free_pages},
{"fs_root", (void *)fs_root},
{"get_cpsr", (void *)get_cpsr},
{"getchar", (void *)getchar},
{"help", (void *)help},
{"init_shell", (void *)init_shell},
{"initial_task_func", (void *)initial_task_func},
{"insert_to_free_area", (void *)insert_to_free_area},
{"irq", (void *)irq},
{"irq_save_spot", (void *)irq_save_spot},
{"is_pllc_invalid", (void *)is_pllc_invalid},
{"k_module_root", (void *)k_module_root},
{"kernel_pgd", (void *)kernel_pgd},
{"kfree", (void *)kfree},
{"kmain", (void *)kmain},
{"kmalloc", (void *)kmalloc},
{"kmalloc_init", (void *)kmalloc_init},
{"kmod_sem", (void *)kmod_sem},
{"kmsg_dump", (void *)kmsg_dump},
{"load_kmodule", (void *)load_kmodule},
{"mask_interrupt", (void *)mask_interrupt},
{"memcmp", (void *)memcmp},
{"memcpy", (void *)memcpy},
{"memmove", (void *)memmove},
{"memset", (void *)memset},
{"mod_output_ops", (void *)mod_output_ops},
{"module_unknown", (void *)module_unknown},
{"next_task", (void *)next_task},
{"oneshot_timer_add", (void *)oneshot_timer_add},
{"pFun", (void *)pFun},
{"page_address", (void *)page_address},
{"page_alloc_init", (void *)page_alloc_init},
{"periodic_timer_add", (void *)periodic_timer_add},
{"platform_fiq", (void *)platform_fiq},
{"platform_init", (void *)platform_init},
{"platform_init_interrupts", (void *)platform_init_interrupts},
{"platform_init_timer", (void *)platform_init_timer},
{"platform_irq", (void *)platform_irq},
{"platform_set_periodic_timer", (void *)platform_set_periodic_timer},
{"pllc_to_busclk", (void *)pllc_to_busclk},
{"prefetch_abort", (void *)prefetch_abort},
{"print_free_list", (void *)print_free_list},
{"printk", (void *)printk},
{"putchar", (void *)putchar},
{"puts", (void *)puts},
{"readline", (void *)readline},
{"register_filesystem", (void *)register_filesystem},
{"register_int_handler", (void *)register_int_handler},
{"reserved", (void *)reserved},
{"reset", (void *)reset},
{"run_command", (void *)run_command},
{"sched_class_fifo", (void *)sched_class_fifo},
{"sched_fifo_init", (void *)sched_fifo_init},
{"sched_init", (void *)sched_init},
{"scheduler", (void *)scheduler},
{"sem", (void *)sem},
{"shell_register_command", (void *)shell_register_command},
{"shell_unregister_command", (void *)shell_unregister_command},
{"show_logo", (void *)show_logo},
{"simple_strtoul", (void *)simple_strtoul},
{"slob_alloc", (void *)slob_alloc},
{"slob_free", (void *)slob_free},
{"slob_new_pages", (void *)slob_new_pages},
{"slob_page_alloc", (void *)slob_page_alloc},
{"stack_top", (void *)stack_top},
{"strcat", (void *)strcat},
{"strchr", (void *)strchr},
{"strcmp", (void *)strcmp},
{"strcpy", (void *)strcpy},
{"strlen", (void *)strlen},
{"strncmp", (void *)strncmp},
{"strncpy", (void *)strncpy},
{"symtab_lookup", (void *)symtab_lookup},
{"syscall", (void *)syscall},
{"task_alloc", (void *)task_alloc},
{"task_bitmap", (void *)task_bitmap},
{"task_create", (void *)task_create},
{"task_create_init", (void *)task_create_init},
{"task_exit", (void *)task_exit},
{"task_free", (void *)task_free},
{"task_init", (void *)task_init},
{"task_schedule", (void *)task_schedule},
{"task_sleep", (void *)task_sleep},
{"timer_delete", (void *)timer_delete},
{"timer_init", (void *)timer_init},
{"timer_list", (void *)timer_list},
{"timer_tick", (void *)timer_tick},
{"undefined", (void *)undefined},
{"undefined_stack", (void *)undefined_stack},
{"undefined_stack_top", (void *)undefined_stack_top},
{"unmask_interrupt", (void *)unmask_interrupt},
{"up", (void *)up},
{"vfs_close", (void *)vfs_close},
{"vfs_lookup", (void *)vfs_lookup},
{"vfs_mount", (void *)vfs_mount},
{"vfs_open", (void *)vfs_open},
{"vfs_read", (void *)vfs_read},
{"virt_to_page", (void *)virt_to_page},
{"vsnprintf", (void *)vsnprintf},
{"zones", (void *)zones},
{"zones_name", (void *)zones_name},
{(char *)0, (void *)0} };
